-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.vendedores
(
    id_vendedor integer,
    nombre character varying NOT NULL,
    ine character varying NOT NULL,
    direccion character varying NOT NULL,
    tipo character varying NOT NULL,
    vendedor_code character varying NOT NULL,
    PRIMARY KEY (id_vendedor),
    UNIQUE (vendedor_code)
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    id_venta integer,
    venta_code character varying NOT NULL,
    medio_pago character varying NOT NULL,
    valor character varying NOT NULL,
    vendedor_code character varying NOT NULL,
    PRIMARY KEY (id_venta),
    UNIQUE (venta_code)
);

CREATE TABLE IF NOT EXISTS public.factura
(
    id_factura integer,
    factura_code character varying NOT NULL,
    venta_code character varying NOT NULL,
    fecha_hora character varying NOT NULL,
    t_veh_venta character varying NOT NULL,
    veh_code character varying NOT NULL,
    adicional_code character varying NOT NULL,
    PRIMARY KEY (id_factura)
);

CREATE TABLE IF NOT EXISTS public.vehiculos
(
    id_vehiculo integer,
    vehiculo_code character varying NOT NULL,
    marca character varying NOT NULL,
    modelo character varying NOT NULL,
    precio character varying NOT NULL,
    descuento character varying NOT NULL,
    potencia_fiscal character varying NOT NULL,
    cilindrada character varying NOT NULL,
    n_bastidor character varying NOT NULL,
    PRIMARY KEY (id_vehiculo),
    UNIQUE (vehiculo_code)
);

CREATE TABLE IF NOT EXISTS public."equipamientoVeh"
(
    id_equipamiento integer,
    equipamiento_code character varying NOT NULL,
    airbag_conductor character varying NOT NULL,
    cierre_centralizado character varying NOT NULL,
    vehiculo_code character varying NOT NULL,
    PRIMARY KEY (id_equipamiento),
    UNIQUE (equipamiento_code)
);

CREATE TABLE IF NOT EXISTS public.adicional
(
    id_adicional integer,
    code_adicional character varying NOT NULL,
    pieza character varying NOT NULL,
    valor character varying NOT NULL,
    vehiculo_code character varying NOT NULL,
    PRIMARY KEY (id_adicional),
    UNIQUE (code_adicional)
);

ALTER TABLE IF EXISTS public.ventas
    ADD FOREIGN KEY (vendedor_code)
    REFERENCES public.vendedores (vendedor_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.factura
    ADD FOREIGN KEY (venta_code)
    REFERENCES public.ventas (venta_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.factura
    ADD FOREIGN KEY (veh_code)
    REFERENCES public.vehiculos (vehiculo_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.factura
    ADD FOREIGN KEY (adicional_code)
    REFERENCES public.adicional (code_adicional) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."equipamientoVeh"
    ADD CONSTRAINT fk_equip_veh FOREIGN KEY (vehiculo_code)
    REFERENCES public.vehiculos (vehiculo_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.adicional
    ADD FOREIGN KEY (vehiculo_code)
    REFERENCES public.vehiculos (vehiculo_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;